name: Build Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'
          check-latest: true

      - name: Build binary for Linux AMD64
        run: GOPROXY=https://goproxy.cn GOOS=linux GOARCH=amd64 go build -o hcache-linux-amd64 -ldflags="-s -w"

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: hcache-linux-amd64
            
